/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.Optional;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Card;
import model.GameCommand;
import model.GameStatus;
import model.Message;
import model.Player;
import model.User;
import service.LarcService;

/**
 *
 * @author ctomazoni
 */
public class MainView extends javax.swing.JFrame {

    LarcService larcService;
    DefaultListModel modelCartasEu = new DefaultListModel();
    DefaultListModel modelCartasOponente = new DefaultListModel();
    
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        larcService = new LarcService();
        new Thread(atualizar).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dsMensagens = new javax.swing.JTextArea();
        mensagem = new javax.swing.JTextField();
        enviarMsgSelec = new javax.swing.JButton();
        enviarMsgTodos = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        listCartasEu = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btJogar = new javax.swing.JButton();
        btParar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        listPlayers = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        btPedir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dsMensagens.setColumns(20);
        dsMensagens.setRows(5);
        dsMensagens.setEnabled(false);
        jScrollPane1.setViewportView(dsMensagens);

        enviarMsgSelec.setText("Enviar mensagem para usuário selecionado");
        enviarMsgSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarMsgSelecActionPerformed(evt);
            }
        });

        enviarMsgTodos.setText("Enviar mensagem para todos os usuários");
        enviarMsgTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarMsgTodosActionPerformed(evt);
            }
        });

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Vitórias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableUser);

        jScrollPane2.setViewportView(listCartasEu);

        jLabel1.setText("Minhas cartas");

        btJogar.setText("Jogar");
        btJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJogarActionPerformed(evt);
            }
        });

        btParar.setText("Parar");
        btParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPararActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(listPlayers);

        jLabel3.setText("Jogadores");

        btPedir.setText("Pedir");
        btPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPedirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mensagem)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btParar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btJogar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btPedir, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enviarMsgSelec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enviarMsgTodos))
                    .addComponent(jScrollPane1))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane5))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btPedir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btJogar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btParar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enviarMsgSelec, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(enviarMsgTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarMsgTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarMsgTodosActionPerformed
        larcService.sendMessage(0, mensagem.getText());
        mensagem.setText("");
    }//GEN-LAST:event_enviarMsgTodosActionPerformed

    private void enviarMsgSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarMsgSelecActionPerformed
        if (tableUser.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione algum usuário!");
        } else if (tableUser.getSelectedRowCount() == 1) {
            larcService.sendMessage((Integer) tableUser.getValueAt(tableUser.getSelectedRow(), 0), mensagem.getText());
            mensagem.setText("");
        } else if (tableUser.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(null, "Selecione apenas um usuário!");
        }
    }//GEN-LAST:event_enviarMsgSelecActionPerformed

    private void btJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJogarActionPerformed
        larcService.sendGame(GameCommand.ENTER);
    }//GEN-LAST:event_btJogarActionPerformed

    private void btPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPararActionPerformed
        larcService.sendGame(GameCommand.STOP);
    }//GEN-LAST:event_btPararActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        larcService.sendGame(GameCommand.QUIT);
    }//GEN-LAST:event_btSairActionPerformed

    private void btPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPedirActionPerformed
        //Listar cartas
        larcService.getCard().ifSuccess(card -> {
            Optional<Card> carta = card;
            if (card.isPresent()) {
                String desc = card.get().getNumber()+card.get().getSuit().getDescricao();
                modelCartasEu.addElement(desc);
            }
        });
        listCartasEu.setModel(modelCartasEu);
    }//GEN-LAST:event_btPedirActionPerformed

    Runnable atualizar = new Runnable() {
        public void run() {
            DefaultTableModel modelUser = (DefaultTableModel) tableUser.getModel();
            DefaultListModel modelPlayer = new DefaultListModel();
            while (true) {
                //Listar usuários
                modelUser.setRowCount(0);
                larcService.getUsers().ifSuccess(users -> {
                    for (User user : users) {
                        modelUser.addRow(new Object [] {
                            user.getId(), user.getName(), user.getWinCount()
                        });
                    }
                });
                
                //Listar jogadores
                modelPlayer.clear();
                larcService.getPlayers().ifSuccess(players -> {
                    for (Player player : players) {
                        modelPlayer.addElement(player.getUserId()+" "+player.getStatus().toString());
                    }
                    if (players.stream().allMatch(player -> player.getStatus().equals(GameStatus.WAITING))) {
                        modelCartasEu.clear();
                    }
                });
                listPlayers.setModel(modelPlayer);
                
                //Listar mensagens
                larcService.getMessage().ifSuccess(message -> {
                    Optional<Message> msg = message;
                    if (msg.isPresent()) {
                        dsMensagens.append(msg.get().getContent()+"\n");
                    }
                });
                
                //Timer
                try {
                    Thread.sleep(6000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }
    };

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btJogar;
    private javax.swing.JButton btParar;
    private javax.swing.JButton btPedir;
    private javax.swing.JButton btSair;
    private javax.swing.JTextArea dsMensagens;
    private javax.swing.JButton enviarMsgSelec;
    private javax.swing.JButton enviarMsgTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> listCartasEu;
    private javax.swing.JList<String> listPlayers;
    private javax.swing.JTextField mensagem;
    private javax.swing.JTable tableUser;
    // End of variables declaration//GEN-END:variables
}
